working-group-two/wgtwo.com

website/src/css/markdown.css
This change adds a little bit of space between the text baseline and the
link underline, to help with readability.
Tested with:
```
$ yarn build
yarn run v1.22.15
$ docusaurus build
[INFO] [en] Creating an optimized production build...
✔ Client
✔ Server
Compiled successfully in 4.53s
✔ Client
● Server █████████████████████████ cache (99%) shutdown IdleFileCachePlugin
stored
[Local Search] [INFO]: Gathering documents
[Local Search] [INFO]: Parsing documents
[Local Search] [INFO]: 3 indexes will be created.
[Local Search] [INFO]: Building index blog_posts_list (20 documents)
[Local Search] [INFO]: Building index default (193 documents)
[Local Search] [INFO]: Building index docs-default-current (57 documents)
[Local Search] [INFO]: Index blog_posts_list written to disk
[Local Search] [INFO]: …
```
=> Fix link underlining CSS

website/src/css/nav.css
Yesterday, after upgrading docusaurus, the hamburger menu on mobile was not responsive due to some inherited CSS from the search. 
This solution will keep the search icon on the right edge and move the hamburger menu to the left side.
=> Fix hamburger menu after upgrade for mobile

website/src/css/common.module.css, website/src/css/general.css, website/src/css/nav.css, website/src/pages/product-ecosystem.module.css, website/src/pages/product-ecosystem.tsx
Button hover effects added to:
- all Primary buttons (those that are black)
- all normal buttons (styled with light-grey border and white background)
- Cancel button for the Search box (the ones that appears after clicking on the Search icon top-right of site)
Additional changes:
- added `transition` property to the navbar "Talk to us" button so that the hover effect is animated
=> Btn Hover Effects added (site-wide)

website/src/components/casestudy/casestudy-list.tsx
The `name` field in casestudy-list.tsx happens to kinda match the id of
the articles in docs/case-studies. So it kinda works. Except it doesn't
lowercase and one name doesn't match.
This isn't great, but this commit does a quick fix, at least.
=> Fix broken (404) links

.github/workflows/website-dev-pages.yml, website/src/pages/test.tsx
With multiple PRs with `devpages` label, an easy way was needed to identify _which_ PR the dev site had deployed the build of. So I modified the Github Action so that the **page title** gets the **PR _name_** and **_number_** appended (hover tab with cursor to see):
=> Add PR Title to Dev site

.github/workflows/website-sync-personio-jobs.yml
This pipeline has been commiting as me. Let's change this ;) 
The changes reference config found https://github.com/peter-evans/enable-pull-request-automerge/blob/main/.github/workflows/ci.yml#L71-L72
16,197 times to be exact
=> Update website-sync-personio-jobs.yml so it doesn't spam my commit history

website/src/theme/BlogPostItem/Footer/index.js
**Issue:** bad coding led to uneven columns when the number of tags were few:
Fixed with this PR :)
=> [Bug] Fixed Bottom Social Buttons bug

website/src/pages/careers.tsx
- Email updated from [victoiria@wgtwo.com](mailto:Victoiria@wgtwo.com) to [hicks@wgtwo.com](mailto:Hicks@wgtwo.com)
- Numbers changed from <code>**60+** engineers, **19+** different nationalities</code> to <code>**75+** engineers, **25+** different nationalities</code>
=> Career Page Text Updated

.github/workflows/website-pr.yml
Runs `yarn prettier` and check if any files were modified, and if they were, commits those changes and pushes, and proceeds with normal procedure.
> Note: a user would have to manually fetch origin for new changes when developing locally (such as when using Github Desktop), and this isn't evident so a user _can_ make more changes locally and push those, only to be met with a warning that there are unfetched commits from origin. Hopefully this isn't a big issue 😅
> 
> ![image](https://user-images.githubusercontent.com/27897747/203394177-636f49c8-855e-427c-a215-6d87a97673c6.png)
=> [GH Action] Auto-Commit Prettier for PR

website/docusaurus.config.js
=> [Fixed] Incorrect Meta/Head Links

.github/workflows/website-dev-pages.yml
The code that adds the PR name to the Title also targeted the Footer Titles. So I've changed to only target the _first occurrence_
Bug:
=> [Bugfix] Devpages Title: only replace first occurrence

website/docusaurus.config.js
We adopted GA4 via GTM (google tag manager) and this removes the GA3 integration.
=> Remove GA3

.github/workflows/website-deploy.yml, .github/workflows/website-dev-pages.yml, .github/workflows/website-pr.yml, .github/workflows/website-sync-personio-jobs.yml, website/src/pages/security.tsx
Fix node 12 deprecation warnings for github actions by upgrading to the latest version
https://github.com/working-group-two/wgtwo.com/actions/runs/4321677432
=> [gh-actions] update to newer versions to fix deprecation warnings

website/src/theme/BlogLayout/styles.module.css, website/src/theme/BlogPostItem/Container/styles.module.css
See this link for the changes made: https://github.com/working-group-two/wgtwo.com/issues/320#issuecomment-1529309389
The fade animation is exclusively kept for the individual blog posts, _not_ the main blog overview page.
=> Pimp the Blog Post Items

website/src/components/contact-form/contact-form.tsx, website/src/pages/contact.tsx, website/src/pages/request-demo.tsx, website/src/pages/security.tsx, website/src/pages/technology.tsx, website/src/util/helpers.js
Help block spam by improving the denylist to include popular email clients like gmail and yahoo, as well as, popular one time email providers that are commonly used by malicious purposes. In the future, we can continue to update this list if we find new domains we should block.
=> Improve email regex for contact form

website/docusaurus.config.js, website/src/css/nav.css, website/static/img/flags/gb.svg, website/static/img/flags/jp.svg
Opted for "English" (instead of "EN").
It's a dropdown :)
=> Navbar Language Switch

website/src/css/nav.css
Fixed the CSS somewhat. Have a look:
https://github.com/working-group-two/wgtwo.com/assets/27897747/a23d41f6-a6f4-4403-9f66-b428f02bfaa5
With Windows emojis:
=> Update Language Switch CSS

website/src/pages/showcase/components/bigTitle.module.css
The blue pill (e.g. "MVO") in the showcase pages wasn't mobile-friendly, so I fixed that :)
=> [Fix] Showcase page Mobile view Pill Visibility

.github/workflows/website-dev-pages.yml
Exclude the Netlify files and folders from being wiped upon deployment of a branch for testing.
Excluded items:
- package.json (used to install sendgrid dependency)
- netlify folder (contains sendmail function)
=> Protect Netlify files in Dev-Pages Branch

docs/about/demos.md, website/src/pages/product-ecosystem.tsx
> link to storefront.wgtwo.com is dead, so removing it
=> Remove Storefront links and references

website/src/css/footer.css
CSS code specifically targets the 6th item in the 2nd column of the footer. As long as this doesn't change, or upon change someone simply changes the hardcoded numbers, this shouldn't be an issue long term :)
=> Added HIRING label to Careers in Footer

website/docusaurus.config.js, website/src/css/announcement-bar.css
*May* break if the infobar's `role="banner"` property is changed somehow, which is quite unlikely. But in such case, simply switch to targeting `div[class^='announcementBar']`
=> Infobar Restyled
