working-group-two/wgtwo.com

docs/about/offices.md, website/.prettierignore, website/src/pages/contact.module.css, website/src/pages/contact.tsx
https://github.com/working-group-two/wgtwo.com/issues/24
=> Add contact information for offices 

website/docusaurus.config.js
Adds keywords to every page on the site https://docusaurus.io/docs/next/seo#global-metadata
Analysis from existing traffic
=> [config] add keywords

website/personio-jobs.xml
Update job positions listing on [the careers page](https://www.wgtwo.com/careers/) using the automated update task when running `yarn start`.
=> Update job positions

website/src/components/integrations/integrations.tsx
=> Add Atos logo to partners logo list on front page

website/src/components/contact-card/contact-card.module.css, website/src/components/employee-quote/employee-quote.module.css, website/src/pages/careers.module.css
* Floats quote images into the text
* Rounds the contact images
=> Improve career page images

website/src/components/contact-card/contact-card.module.css, website/src/components/employee-quote/employee-quote.module.css, website/src/pages/careers.module.css
More info on the subject: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image
=> Fix contact images on career page, try 2

website/src/components/logs/logs.tsx, website/src/components/rbe/rbe.tsx
=> Fix small language/text issues

website/src/pages/contact.module.css, website/src/pages/contact.tsx, website/src/pages/request-demo.tsx, website/src/pages/technology.tsx, website/src/util/helpers.ts
=> Validate email address before submitting forms

website/src/components/company-profile/company-profile.module.css, website/src/components/company-profile/company-profile.tsx, website/src/pages/index.tsx
=> Add company profile component to jp front page

website/src/components/casestudy/casestudy-list.tsx
=> Small text changes to case studies

.github/workflows/website-pr.yml, blog/2019-12-20-jenkins-to-concourse.md, blog/2020-05-18-formatting-erlang.md, blog/2020-08-28-a-new-hope-for-products-in-telecom.md, blog/2020-12-11-forbidden-lore-hacking-dns-routing-for-k8s.md, blog/2021-01-07-mqtt-event-bridge.md, blog/2021-02-28-kafka-timers.md, docs/about/demos.md, docs/about/working-with-wgtwo.md, website/docusaurus.config.js, website/i18n/jp/docusaurus-theme-classic/footer.json, website/linkinator.config.json, website/package.json, website/src/pages/product-ecosystem.tsx, website/src/pages/team.tsx, website/yarn.lock
* Fixes broken links
* http -> https for all found offenders
* Will check for broken links on PR checks
=> Fix broken links and add link checking in PRs

website/docusaurus.config.js, website/src/components/ourservice/ourservice.tsx, website/src/components/security-domain/security-domain.tsx, website/src/components/security-header/security-header.module.css, website/src/components/security-header/security-header.tsx, website/src/components/security-links/security-links.tsx, website/src/pages/security.tsx
- add a reference to trust.wgtwo.com in footer
- update the wgtwo.com/security page to add a new component to handle links
- cleanup some unused code in the security page
=> [security] add security trust

.github/workflows/website-dev-pages.yml
Okay, now I'm fairly confident this is going to work. "Forgot" to checkout to the PR branch...
Remember when I said I had Github Actions figured out? Yeah, that was the Dunning-Kruger effect speaking 😅
=> Fixed Github Action - Dev site

website/src/pages/techco.module.css, website/src/pages/techco.tsx
=> TechCo Generator - Fixed Mobile Styling

website/src/pages/techco.module.css, website/src/pages/techco.tsx
=> Generate Again Button - Text Fixed

website/docusaurus.config.js, website/package.json, website/yarn.lock
Allows you to write 
```
```mermaid
graph TD;
A-->B;
A-->C;
B-->D;
C-->D;
```
```
in markdown.
=> Add ```mermaid fenced-code-blocks in markdown

website/i18n/jp/code.json, website/src/components/casestudy/casestudy.module.css, website/src/components/casestudy/casestudy.tsx, website/src/components/company-profile/company-profile.tsx, website/src/components/cta/cta.tsx, website/src/components/enterprise/enterprise.module.css, website/src/components/enterprise/enterprise.tsx, website/src/components/hero/hero.tsx, website/src/components/logs/logs.tsx, website/src/components/quote/quote.module.css, website/src/components/quote/quote.tsx, website/src/components/rbe/rbe.module.css, website/src/components/rbe/rbe.tsx, website/src/css/common.module.css
=> Home text translated into Japanese.

website/src/pages/technology.tsx
From https://github.com/working-group-two/wgtwo.com/issues/153
=> Fixed Text on Technology page

blog/2022-10-13-product-bundling/index.md, blog/2022-11-21-snowcone/index.md, docs/about/introduction.md
This pr combines #170 and #187 as there were issues with github ci building.
=> Updates to various blog posts and doc

website/src/css/general.css
- Footer now full-length
Note: haven't extensively tested this to see if there are any side-effects on mobile version or not 😅
-----
=> [Fixed] Full Docs Width

website/i18n/jp/code.json, website/src/components/newsletter-signup/newsletter-signup.tsx, website/src/pages/newsletter-signup.module.css, website/src/pages/newsletter-signup.tsx
- Make new Page: /newsletter-signup
- Edit NewsletterSignup component to accept className prop
=> Newsletter Signup Created!

website/src/components/technologymetrics/technologymetrics-list.tsx
=> Update Technology Metrics

website/personio-jobs.xml, website/src/pages/contact.module.css, website/src/pages/contact.tsx, website/src/pages/request-demo.tsx, website/src/pages/security.tsx, website/src/pages/technology.tsx, website/src/util/helpers.js
**Changes:**
- Added regex to check for < and >
- Refactored code a bit to better highlight the element containing the error
**Pages:**
- /contact
- /request-demo
- /technology
**Improvement suggestions:**
- Combine all the 3 forms into a single Component that can easily be edited/customized to avoid repeating the code
=> Angle Brackets Check for Contact Forms

website/src/components/technologymetrics/technologymetrics-list.tsx
> wgtwo-console > Send SMS to:
> wgtwo-console > @torotimes 
> wgtwo-console > Enter message:
> wgtwo-console > The SMS number in the Technology page has now been updated to reflect the most current statistical figures. Please approve this PR to see the changes. \\(0^◇^0)/
> wgtwo-console: Type PIN code:
> wgtwo-console: ****
=> Update SMS Figure

website/src/theme/BlogPostItem/Container/styles.module.css, website/src/theme/BlogPostItem/Content/styles.module.css, website/src/theme/BlogPostItem/FeaturedImage/styles.module.css, website/src/theme/BlogPostItem/Header/Author/styles.module.css
Needs to be `display: inline`, apparently: https://stackoverflow.com/a/72170897
=> fix: sarfari line-clamp on blogpost cards, refs #253

website/src/theme/BlogLayout/index.js, website/src/theme/BlogLayout/styles.module.css
Beware, the blog post isn't centered anymore. Probably intended, right? 😅
=> [Blog] Custom CSS Column Values

website/src/pages/contact.module.css
Original fix done here https://github.com/working-group-two/wgtwo.com/pull/312 and fixes https://github.com/working-group-two/wgtwo.com/issues/296
=> Update contact.module.css to fix spanning out of screen

website/src/components/contact-card/contact-card.module.css
=> Center Text of Contact Cards (in /Careers)

blog/2023-04-17-trailblazing-product-developers/index.md
Approve this PR so I can fix the other :)
=> Disable OnRelay.com URL
